# Generated by Django 5.1 on 2024-12-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assemblies", "0002_remove_assembly_package"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="assembly",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="assemblies.assembly",
            ),
        ),
    ]
