# Generated by Django 5.1 on 2024-09-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets/'),
        ),
    ]
