# Generated by Django 5.1 on 2026-03-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        ("categories", "0001_initial"),
        ("components", "0007_alter_component_price"),
        ("packages", "0001_initial"),
        ("sub_categories", "0002_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="equivalent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equivalents",
                to="components.component",
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="component_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__gte", 0), ("price__isnull", True), _connector="OR"
                ),
                name="component_price_non_negative",
            ),
        ),
    ]
