# Generated by Django 5.1 on 2026-05-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0009_componentsupplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentsupplier",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="componentsupplier",
            name="is_default",
        ),
    ]
