name: Automatic Pull Request pipeline

on: [push, pull_request]

jobs:
  AutoPR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      
      - name: Create python venv
        run: python -m venv venv

      - name: Install dev dependencies
        run: venv/bin/python -m pip install -r requirements_dev.txt

      - name: Run Static analysis
        run: venv/bin/python -m flake8
