name: Auto Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  AutoRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Create Python venv
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install commitizen

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
