name: Auto Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  AutoRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Create Python venv
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install commitizen

      - name: Bump Version
        run: |
          if [ -z "$(git log $(git describe --tags --abbrev=0)..HEAD)" ]; then
            echo "No new commits since last tag. Skipping cz bump."
          else
            echo "VERSION = \"$NEW_VERSION\"" > app/version.py
            venv/bin/cz bump --yes
            venv/bin/python -m commitizen bump --yes
          fi

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): bump version to $NEW_VERSION and update changelog"
          git push origin main --tags
