name: Auto Pull Request Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  AutoPR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Create Python venv
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install -r requirements_dev.txt black isort commitizen

      - name: Check Code Formatting with Black
        run: venv/bin/black --check .

      - name: Check Import Sorting with Isort
        run: venv/bin/isort --check .

      # Validate the PR title (for squash merges)
      - name: Validate Pull Request Title
        if: github.event_name == 'pull_request'
        run: venv/bin/python -m commitizen check --message "${{ github.event.pull_request.title }}"

      - name: Fetch tags
        run: git fetch --tags --prune --unshallow || git fetch --tags

      - name: Bump Version
        run: |
          set +e  # Disable errexit to allow non-zero exit codes without stopping the script

          OUTPUT=$(venv/bin/cz bump --yes 2>&1)
          EXIT_CODE=$?

          set -e  # Re-enable errexit now that we have captured the exit code

          if [[ "$OUTPUT" == *"[NO_COMMITS_TO_BUMP]"* ]]; then
              echo "No commits eligible for bump. Exiting without error."
              exit 0
          elif [ $EXIT_CODE -ne 0 ]; then
              echo "An unexpected error occurred during cz bump."
              echo "$OUTPUT"
              exit $EXIT_CODE
          else
              echo "Version bumped successfully."
          fi
