name: Auto Pull Request Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  AutoPR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Create Python venv
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install -r requirements_dev.txt
          venv/bin/python -m pip install -r requirements.txt

      - name: Check Code Formatting with Black
        run: venv/bin/black --check .

      - name: Check Import Sorting with Isort
        run: venv/bin/isort --check .

      - name: Run unit tests
        env:
          SECRET_KEY: ${{ secrets.SGC_DJANGO_SECRET_KEY }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SGC_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SGC_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
        run: venv/bin/python manage.py test

      # Validate the PR title (for squash merges)
      - name: Validate Pull Request Title
        if: github.event_name == 'pull_request'
        run: venv/bin/python -m commitizen check --message "${{ github.event.pull_request.title }}"
